
export const GET_DATA_REQUEST="GET_DATA_REQUEST"
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS"
export const GET_DATA_ERROR="GET_DATA_ERROR"


export const POST_DATA_REQUEST="POST_DATA_REQUEST"
export const POST_DATA_SUCCESS="POST_DATA_SUCCESS"
export const POST_DATA_ERROR="POST_DATA_ERROR"

export const SET_AUTH_DATA="SET_AUTH_DATA"
export const SET_LOGOUT="SET_LOGOUT"