export const FETCH_REQUEST="FETCH_REQUEST"
export const FETCH_FAILUE="FETCH_FAILUE"
export const FETCH_MEN_SUCCESS="FETCH_MEN_SUCCESS"
export const FETCH_WOMEN_SUCCESS="FETCH_WOMEN_SUCCESS"
export const FETCH_ACCESORIES_SUCCESS="FETCH_ACCESORIES_SUCCESS"

